# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reconstruction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14reconstruction.proto\x12\x0ereconstruction\",\n\nSfMRequest\x12\x13\n\x06userid\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\t\n\x07_userid\",\n\nMVSRequest\x12\x13\n\x06userid\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\t\n\x07_userid\"0\n\x0eTextureRequest\x12\x13\n\x06userid\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\t\n\x07_userid\"\"\n\x08SfMReply\x12\x0f\n\x02ok\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x05\n\x03_ok\"\"\n\x08MVSReply\x12\x0f\n\x02ok\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x05\n\x03_ok\"&\n\x0cTextureReply\x12\x0f\n\x02ok\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x05\n\x03_ok2\xd9\x01\n\x0eReconstruction\x12=\n\x03SfM\x12\x1a.reconstruction.SfMRequest\x1a\x18.reconstruction.SfMReply\"\x00\x12=\n\x03MVS\x12\x1a.reconstruction.MVSRequest\x1a\x18.reconstruction.MVSReply\"\x00\x12I\n\x07Texture\x12\x1e.reconstruction.TextureRequest\x1a\x1c.reconstruction.TextureReply\"\x00\x62\x06proto3')



_SFMREQUEST = DESCRIPTOR.message_types_by_name['SfMRequest']
_MVSREQUEST = DESCRIPTOR.message_types_by_name['MVSRequest']
_TEXTUREREQUEST = DESCRIPTOR.message_types_by_name['TextureRequest']
_SFMREPLY = DESCRIPTOR.message_types_by_name['SfMReply']
_MVSREPLY = DESCRIPTOR.message_types_by_name['MVSReply']
_TEXTUREREPLY = DESCRIPTOR.message_types_by_name['TextureReply']
SfMRequest = _reflection.GeneratedProtocolMessageType('SfMRequest', (_message.Message,), {
  'DESCRIPTOR' : _SFMREQUEST,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.SfMRequest)
  })
_sym_db.RegisterMessage(SfMRequest)

MVSRequest = _reflection.GeneratedProtocolMessageType('MVSRequest', (_message.Message,), {
  'DESCRIPTOR' : _MVSREQUEST,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.MVSRequest)
  })
_sym_db.RegisterMessage(MVSRequest)

TextureRequest = _reflection.GeneratedProtocolMessageType('TextureRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTUREREQUEST,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.TextureRequest)
  })
_sym_db.RegisterMessage(TextureRequest)

SfMReply = _reflection.GeneratedProtocolMessageType('SfMReply', (_message.Message,), {
  'DESCRIPTOR' : _SFMREPLY,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.SfMReply)
  })
_sym_db.RegisterMessage(SfMReply)

MVSReply = _reflection.GeneratedProtocolMessageType('MVSReply', (_message.Message,), {
  'DESCRIPTOR' : _MVSREPLY,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.MVSReply)
  })
_sym_db.RegisterMessage(MVSReply)

TextureReply = _reflection.GeneratedProtocolMessageType('TextureReply', (_message.Message,), {
  'DESCRIPTOR' : _TEXTUREREPLY,
  '__module__' : 'reconstruction_pb2'
  # @@protoc_insertion_point(class_scope:reconstruction.TextureReply)
  })
_sym_db.RegisterMessage(TextureReply)

_RECONSTRUCTION = DESCRIPTOR.services_by_name['Reconstruction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SFMREQUEST._serialized_start=40
  _SFMREQUEST._serialized_end=84
  _MVSREQUEST._serialized_start=86
  _MVSREQUEST._serialized_end=130
  _TEXTUREREQUEST._serialized_start=132
  _TEXTUREREQUEST._serialized_end=180
  _SFMREPLY._serialized_start=182
  _SFMREPLY._serialized_end=216
  _MVSREPLY._serialized_start=218
  _MVSREPLY._serialized_end=252
  _TEXTUREREPLY._serialized_start=254
  _TEXTUREREPLY._serialized_end=292
  _RECONSTRUCTION._serialized_start=295
  _RECONSTRUCTION._serialized_end=512
# @@protoc_insertion_point(module_scope)
